import type { FonctionItem, MembreProfile, ProfilFields } from "../api.js";
import { useT } from "../i18n.js";
import { T } from "../proto.js";
import { RecapRow } from "./CompleterProfilParts.js";

/**
 * The last step of the registration wizard: everything the member is about to
 * submit, read-only, with what is still missing said plainly.
 *
 * Extracted from the wizard, which had grown well past the size this project allows.
 * This step was the natural first piece to leave: it only reads, so it needs no
 * handler and cannot change anything, and pulling it out removes a block of markup
 * without moving any behaviour.
 *
 * Nothing here is editable on purpose. A member who spots a mistake goes back to the
 * step that owns the field, so a value is only ever entered in one place and the
 * checks of that step always apply to it.
 */
export function CompleterRecap({
  profile,
  f,
  commissionNom,
  rattachementTxt,
  tribuNom,
  axeOk,
  fonctions,
  labelFonction,
  photoOk,
  pieceOk,
  signed,
}: Readonly<{
  profile: MembreProfile | null;
  f: ProfilFields;
  commissionNom: string;
  rattachementTxt: string;
  tribuNom: string;
  axeOk: boolean;
  fonctions: FonctionItem[];
  /** Resolves a function's label in the member's own gender. */
  labelFonction: (fn: FonctionItem) => string;
  photoOk: boolean;
  pieceOk: boolean;
  signed: boolean;
}>): JSX.Element {
  const t = useT();
  const souhaitees = f.fonctions_souhaitees ?? [];

  return (
    <>
      <p style={{ fontSize: 12, color: T.mut, lineHeight: 1.5, margin: "10px 2px 8px" }}>{t("completer.recapIntro")}</p>
      {/* The ADSUM matricule is generated by the system at account creation and can
          never be typed or edited: it is shown read-only so the member knows their
          reference before submitting. */}
      {profile?.matricule && (
        <RecapRow label={t("completer.recapMatricule")} value={profile.matricule} ok />
      )}
      {f.code_membre?.trim() && (
        <RecapRow label={t("completer.fCodeMembre")} value={f.code_membre.toUpperCase()} ok />
      )}
      <RecapRow label={t("completer.recapNom")} value={`${f.prenoms} ${f.nom}`.trim() || t("completer.recapEmpty")} ok={!!(f.prenoms && f.nom)} />
      <RecapRow label={t("completer.recapTelephone")} value={f.telephone ? `${f.indicatif_telephone ?? ""} ${f.telephone}` : t("completer.recapEmpty")} ok={!!f.telephone} />
      <RecapRow label={t("completer.recapPaysVille")} value={[f.pays, f.ville].filter(Boolean).join(", ") || t("completer.recapEmpty")} ok={!!(f.pays && f.ville)} />
      <RecapRow label={t("completer.recapCommission")} value={commissionNom || t("completer.recapNotChosenF")} ok={!!f.commission_id} />
      <RecapRow label={t("completer.recapRattachement")} value={rattachementTxt || t("completer.recapNotChosenM")} ok={axeOk} />
      <RecapRow label={t("completer.recapTribu")} value={tribuNom || t("completer.recapNotChosenF")} ok={!!f.tribu_id} />
      {f.berger_declare && (
        <RecapRow label={t("completer.fBergerDeclare")} value={`${t("completer.bergerOui")}${f.berger_nom_declare ? ` (${f.berger_nom_declare})` : ""}`} ok />
      )}
      {souhaitees.length > 0 && (
        <RecapRow
          label={t("completer.blocFonction")}
          value={souhaitees
            .map((s) => {
              const fn = fonctions.find((x) => x.cle === s.cle);
              const lib = fn ? labelFonction(fn) : s.cle;
              return s.perimetre ? `${lib} (${s.perimetre})` : lib;
            })
            .join(", ")}
          ok
        />
      )}
      {(f.baptise || f.premiere_communion || f.confirme) && (
        <RecapRow
          label={t("completer.secVieSpirituelle")}
          value={[
            f.baptise ? t("completer.fBaptise") : "",
            f.premiere_communion ? t("completer.fPremiereCommunion") : "",
            f.confirme ? t("completer.fConfirme") : "",
          ].filter(Boolean).join(", ")}
          ok
        />
      )}
      <RecapRow label={t("completer.recapPhoto")} value={photoOk ? t("completer.recapProvided") : t("completer.recapMissing")} ok={photoOk} />
      <RecapRow label={t("completer.recapPiece")} value={pieceOk ? t("completer.recapProvided") : t("completer.recapMissing")} ok={pieceOk} />
      <RecapRow label={t("completer.recapSignature")} value={signed ? t("completer.recapVerified") : t("completer.recapMissing")} ok={signed} />
    </>
  );
}
